# Generated by Django 3.0.2 on 2020-01-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='key',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
